### ISSUE TITLE
Error= Needs Browser (I have already done display unlock and i dont have 2FA activate)

### ISSUE THREAD

**Issue by sspacenerd** [B16f00t/whapa#114]
Hi there! I have already done Display Unlock captcha and I dont have any 2FA ON, this is what it shows on the terminal: Is the first time that this happend to me, i've using this tool since a couple of months now and suddenly it stoped working [
![Screenshot_14](https://user-images.githubusercontent.com/63374594/122373657-a8f56880-cf2f-11eb-9fd8-2bc0b4f7e924.jpg)
](url)

**Comment by User1920ca** [comment]
Same problem

**Comment by dilinjabass** [comment]
Same issue. Have a fresh install of this program too. In another issue ticket someone said that running "pip install --upgrade -r ./doc/requirements.txt" solved the issue for him, doesnt solve it for me (using pip3, if it make any difference).

When I run install on requirements I do get some errors however:

`
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h9aqykd7/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h9aqykd7/cryptography/
`

**Comment by TITAN6146** [comment]
Tengo el mismo problema por favor arreglarlo

**Comment by TehBotolSosro** [comment]
i also have the same issue here, it used to work fine without issue, but now having the same error, i read someone here solved it by upgrading the requirement but i try it along with upgrading the python version and still not working

i also tried to upgrade the gpsoauth to v 1 but it cause issue (something about signature error).
i also cannot create app password and name in google since the account doesn't have 2fa on

so i don't know why suddenly it doesn't work, does google change something?

**Comment by B16f00t** [comment]
Same Issue #106
