### ISSUE TITLE
Unable to locate google drive file map for: com.whatsapp

### ISSUE THREAD

**Issue by maamirh** [B16f00t/whapa#26]
I tried many solutions and follow every guide but i am getting this error "Unable to locate google drive file map for: com.whatsapp" every time .

Every thing was working fine before .I am getting this error from some days .I think google or whatsapp changed the policies .

Kindly handle this issue.

**Comment by B16f00t** [comment]
Ok in principle, the accounts I've tried work perfectly. I'm trying to get some account out of that error to analyze the requests. So so far we have to wait for it to fix the problem.

**Comment by BriggBongo** [comment]
Have you recently changed phone(but migrated WhatsApp number to the other new phone in the same Google drive account) since it broke with that message? 

Also have you tried to initiate a new backup via the phone manually? 

I am also trying to find a common denominator.

Only thing that's changed since it stopped working for me is i bought a new phone (galaxy s10 android pie with latest whatsapp as at sept 2019) and migrated my WhatsApp number to the new phone so upon installing WhatsApp it downloaded a cooy of my data via the same Google identity and has been backing up successfully since then. The other phone was decommissioned and factory reset. Nothing changed in the config and i get same error as you.

Further more i started with a fresh log file and folder for the backup repo but same error.

**Comment by TehBotolSosro** [comment]
if i tried the normal method it give me "Unable to locate google drive file map for: com.whatsapp"
but changing it to the alternate download method works fine without issue
so try the alternate download option

**Comment by BriggBongo** [comment]
Alternative version works from. Issue was with spacing in the cfg file.

**Comment by maamirh** [comment]
Alternate method is working and resolved my issue.
