### ISSUE TITLE
Problem Installalling on Xubuntu 20.04.

### ISSUE THREAD

**Issue by Pj1907** [B16f00t/whapa#83]
Hi.
I can't finalize installation on Xubuntu 20.04:

git clone https://github.com/B16f00t/whapa.git    ----- ok done

sudo apt install python3-tk    ---- ok done

pip3 install -r ./doc/requirements.txt    ----- ERROR: Could not open requirements file: [Errno 2] File o directory non esistente: './doc/requirements.txt

Thanks.

**Comment by B16f00t** [comment]
are you sure that the file exist? are you in the correct path?

**Comment by Pj1907** [comment]
Yes.:  /home/(my user)/whapa/doc/requirements.txt

It contain this:

pycryptodome
colorama
configparser
gpsoauth
requests==2.21.0

**Comment by Joeldevfront-end** [comment]
Não Sei falar inglês, portanto não entendo o que estas a falar Enviado do meu celular Huawei-------- Mensagem Original --------Assunto:Re: [B16f00t/whapa] Problem Installalling on Xubuntu 20.04. (#83)De:Ivan Moreno Para:B16f00t/whapa Cc:Subscribed 
are you sure that the file exist? are you in the correct path?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/B16f00t/whapa/issues/83#issuecomment-765892227",
"url": "https://github.com/B16f00t/whapa/issues/83#issuecomment-765892227",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by B16f00t** [comment]
Sorry, but I don't understand what you show me

**Comment by Pj1907** [comment]
Ivan, you asked to me if the file exist... isn't it?

And I replied that it exist in this path:

/home/(my user)/whapa/doc/requirements.txt

And this is what such "requirements.txt"  file contains:

"
pycryptodome
colorama
configparser
gpsoauth
requests==2.21.0
"

Sorry if I was not clear enough.
Piergiorgio

**Comment by B16f00t** [comment]
The error it shows is that the file path does not exist.
I don't know if you have configured the permissions correctly.
Try to install the requirements by hand with:
pip3 install pycryptodome colorama configparser gpsoauth requests==2.21.0

**Comment by Pj1907** [comment]
Hi,
done.

Installing collected packages: pycryptodome, configparser, pycryptodomex, urllib3, requests, gpsoauth
Successfully installed configparser-5.0.1 gpsoauth-0.4.1 pycryptodome-3.9.9 pycryptodomex-3.9.9 requests-2.21.0 urllib3-1.24.3

But when I digit:

~$ python3 whapa-gui.py

This is what I get:

python3: can't open file 'whapa-gui.py': [Errno 2] No such file or directory

And also If I digit:

pip3 install -r ./doc/requirements.txt 
or 
sudo pip3 install -r ./doc/requirements.txt

I get ;
ERROR: Could not open requirements file: [Errno 2] File o directory non esistente: './doc/requirements.txt'

**Comment by B16f00t** [comment]
It seems that you don't have permissions, so you must change it, with chmod for example
